Task 02-accordion
js-tasks-ru/htmlcss-20210708_asdf-yura pull request #3
Opened 2021-07-14 08:56 UTC by yura2015

2021-07-14 08:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-14 12:06 UTC, GSemikozov requested changes

2021-07-14 12:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary {
в БЭМ мы избегаем селекторов тегов, поэтому - summary -> .accordion

2021-07-14 18:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-15 13:32 UTC, GSemikozov approved these changes

2021-07-15 13:32 UTC, merged