Histogram
js-tasks-ru/htmlcss-20210708_asdf-yura pull request #5
Opened 2021-07-18 15:04 UTC by yura2015

2021-07-18 15:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-18 15:37 UTC, GSemikozov requested changes

2021-07-18 15:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin:0px;
они ведь и так нулевые) а вот если мы в блоке задаем марджины, то через другой класс-микс возможно придется перебивать стили через !important если будет недостаточно специфичности. Так что лучше удалить

2021-07-18 15:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    min-width:0;
здесь и ниже - нет смысла задавать минимальную ширину = 0

2021-07-18 15:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
точно ли на. уровне блока необходимо такое выравнивание?

2021-07-18 17:27 UTC, yura2015 commented on 04-lection2/01-histogram/histogram.css
> +    margin:0px;
Исправил. Согласен, это перебор.

2021-07-18 17:30 UTC, yura2015 commented on 04-lection2/01-histogram/histogram.css
> +    min-width:0;
Исправил. Хотел обеспечить максимальное сжатие.

2021-07-18 17:39 UTC, yura2015 commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
Исправил.

2021-07-18 17:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-19 07:41 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    min-width:0;
это лучше делать с помощью flex-shrink

2021-07-19 08:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-19 08:38 UTC, GSemikozov approved these changes

2021-07-19 08:38 UTC, merged