02-modal of 05-lection3 in master
js-tasks-ru/htmlcss-20210708_asdf-yura pull request #9
Opened 2021-07-21 19:44 UTC by yura2015

2021-07-21 19:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-22 06:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-22 13:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-23 14:22 UTC, GSemikozov requested changes

2021-07-23 14:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 355px;
проще было бы привязаться к правому краю) особенно с учетом того, что размеры модалки будут меняться на мобилке

2021-07-23 14:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button
кнопки у нас уже реализованы, нужно переиспользовать готовый компонент, а не дублировать код

2021-07-23 17:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-23 17:55 UTC, yura2015 commented on 05-lection3/02-modal/modal.css
> +    left: 355px;
Исправил

2021-07-23 17:55 UTC, yura2015 commented on 05-lection3/02-modal/modal.css
> +.button
Исправил

2021-07-24 08:46 UTC, GSemikozov requested changes

2021-07-24 08:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    right: -355px;
ноу) 
```
position: absolute;
right: 16px;
```

2021-07-24 13:02 UTC, yura2015 commented on 05-lection3/02-modal/modal.css
> +    right: -355px;
исправил

2021-07-24 13:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-24 13:11 UTC, GSemikozov approved these changes

2021-07-24 13:11 UTC, merged